package xplr.in.currencycalculator;


import android.content.Context;
import android.content.SharedPreferences;

import org.greenrobot.eventbus.EventBus;

import javax.inject.Named;
import javax.inject.Singleton;

import dagger.Module;
import dagger.Provides;
import xplr.in.currencycalculator.sources.HttpRateSource;
import xplr.in.currencycalculator.sources.RateSource;
import xplr.in.currencycalculator.sources.ResRawRateSource;


/**
 * Dagger2 module.
 *
 * Most of these @Singleton's can be @Resusable when it becomes available. Just not EventBus.
 */
@Module
public class AppModule {

    private final App app;

    public AppModule(App app) {
        this.app = app;
    }

    @Provides @Singleton EventBus provideEventBus() {
        return new EventBus();
    }

    @Provides @Singleton App provideApplication() {
        return app;
    }

    // Changes to package structure and class names will change the key generated by default. Be
    // specific to avoid "loosing" preferences by accident later.
    private static final String APP_SHARED_PREFERENCES_KEY = "xplr.in.currencycalculator.app_preferences";
    @Provides @Singleton SharedPreferences provideAppSharedPrefs() {
        return app.getSharedPreferences(APP_SHARED_PREFERENCES_KEY, Context.MODE_PRIVATE);
    }

    @Provides @Singleton @Named("remote")
    RateSource provideRemoteRateSource() {
        return new HttpRateSource();
    }

    @Provides @Singleton @Named("local")
    RateSource provideLocalRateSource() {
        return new ResRawRateSource(app);
    }
}
