package xplr.in.currencycalculator;


import android.content.Context;
import android.content.SharedPreferences;

import org.greenrobot.eventbus.EventBus;

import javax.inject.Named;
import javax.inject.Singleton;

import dagger.Module;
import dagger.Provides;
import xplr.in.currencycalculator.sources.CurrencySource;
import xplr.in.currencycalculator.sources.HttpCurrencySource;
import xplr.in.currencycalculator.sources.ResRawCurrencySource;


/**
 * Dagger2 module.
 *
 * Most of these @Singleton's can be @Resusable when it becomes available. Just not EventBus.
 */
@Module
public class AppModule {

    private final App app;

    public AppModule(App app) {
        this.app = app;
    }

    @Provides @Singleton EventBus provideEventBus() {
        return new EventBus();
    }

    @Provides @Singleton App provideApplication() {
        return app;
    }

    @Provides @Singleton CurrencySource provideCurrencySource() {
        return new HttpCurrencySource();
    }

    // Changes to package structure and class names will change the key generated by default. Be
    // specific to avoid "loosing" preferences by accident later.
    private static final String APP_SHARED_PREFERENCES_KEY = "xplr.in.currencycalculator.app_preferences";
    @Provides @Singleton SharedPreferences provideAppSharedPrefs() {
        return app.getSharedPreferences(APP_SHARED_PREFERENCES_KEY, Context.MODE_PRIVATE);
    }

    @Provides @Singleton @Named("remote") CurrencySource provideRemoteCurrencySource() {
        return new HttpCurrencySource();
    }

    @Provides @Singleton @Named("local") CurrencySource provideLocalCurrencySource() {
        return new ResRawCurrencySource(app);
    }
}
